name: Home Assistant config check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Az action maga másolja a mintát ./secrets.yaml-ként
      - uses: frenck/action-home-assistant@v1
        with:
          path: "."
          secrets: secrets.example.yaml
          version: stable
